import './laisin-js/sweetalert.all.js'
import './laisin-js/live-search.js'
import './laisin-js/hamburger.js'
import './laisin-js/laisin-product.js'
import './laisin-js/contact.js'
import './laisin-js/laisin-uploadfile.js'
import './laisin-js/confirmdelete.js'
import './laisin-js/laisin-chart.js'
import './laisin-js/laisin-admin.js'
import './bootstrap'

